name: Process Modified Files in config Folder

on: [push]

jobs:
  process_modified_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full commit history is available


      - name: Get Modified Files in config Folder
        id: changed_files
        run: |
          MODIFIED_FILES=$(git diff --name-only HEAD~1 HEAD -- config/)
          echo "Modified files: $MODIFIED_FILES"
          echo "FILES=$MODIFIED_FILES" >> $GITHUB_ENV

      - name: Run Python Script with Modified Files
        run: |
          if [ -n "$FILES" ]; then
            python listfiles.py $FILES
          else
            echo "No modified files in config/ folder. Skipping script execution."
          fi
