name: Get Modified Config Files and Run Python Script

on:
  push:
    branches:
      - main  # Runs when changes are merged into 'main'

jobs:
  get-modified-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to compare changes

      - name: Get Last Commit Before Merge
        id: previous_commit
        run: echo "BASE_SHA=$(git rev-parse HEAD~1)" >> $GITHUB_ENV

      - name: Get Modified Files
        id: modified_files
        run: |
          MODIFIED_FILES=$(git diff --name-only $BASE_SHA HEAD)
          echo "Modified files:"
          echo "$MODIFIED_FILES"

          # Store all modified files in GITHUB_ENV
          echo "FILES=$MODIFIED_FILES" >> "$GITHUB_ENV"


      - name: Process Modified Files
        run: |
          echo "Files changed in this merge:"
          echo "$FILES"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: python -m pip install --upgrade pip

      - name: Run Python Script with Modified Files
        run:| 
          python listfiles.py
        env:
          files: ${{ env.files }}