jobs:
  get-modified-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to compare changes

      - name: Get Last Commit Before Merge
        id: previous_commit
        run: echo "BASE_SHA=$(git rev-parse HEAD~1)" >> $GITHUB_ENV

      - name: Get Modified Files
        id: modified_files
        run: |
          MODIFIED_FILES=$(git diff --name-only $BASE_SHA HEAD)
          echo "Modified files:"
          echo "$MODIFIED_FILES"

          # Store all modified files in GITHUB_ENV
          echo "FILES=$MODIFIED_FILES" >> "$GITHUB_ENV"

          # Filter and store only config files in GITHUB_ENV
          CONFIG_FILES=$(echo "$MODIFIED_FILES" | grep '^config/' || true)
          echo "CONFIG_FILES=$CONFIG_FILES" >> "$GITHUB_ENV"

      - name: Process Modified Files
        run: |
          echo "Files changed in this merge:"
          echo "$FILES"  # Optional: prints all modified files for debugging
          echo "Config files changed in this merge:"
          echo "$CONFIG_FILES"  # Prints only files inside 'config/'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: python -m pip install --upgrade pip

      - name: Run Python Script with Modified Config Files
        run: python listfiles.py "$CONFIG_FILES"
