name: Process Modified Files in ABC Folder

on: [push]

jobs:
  process_modified_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Modified Files in config Folder
        id: changed_files
        run: |
          MODIFIED_FILES=$(git diff --name-only HEAD^ HEAD -- config/)
          echo "Modified files: $MODIFIED_FILES"
          echo "FILES=$MODIFIED_FILES" >> $GITHUB_ENV

      - name: Run Python Script with Modified Files
        run: |
          if [ -n "$FILES" ]; then
            poetry run python test.py $FILES
          else
            echo "No modified files in config/ folder. Skipping script execution."
          fi
